### PR TITLE
fix shooting when selecting an option if a player has a gun out.

### PR DESCRIPTION
**Pull request by IdrisDose**
* Added the following code in replace of straight asssignments, I'm not sure if there is uintended sideffects but from testing this has prevented me from firing a gun if I have one out after selecting an option.
```lua
SetTimeout(1000, function()
	targetActive, success, hasFocus = false, false, false
end)
```

*the other changes are editor line ending changes...

### CODE REVIEW

**Comment by BerkieBb** [comment]
Can you check if you can get it from 1000 to any lower? As I want to make sure it can't conflict with the other stuff

**Comment by IdrisDose** [comment]
@BerkieBb sure I'll have a peep tomorrow, I'm testing on a onesync server.

**Comment by IdrisDose** [comment]
So I converted it to a config option so that users can increase if they can still, the lowest I was able to get consistent results for was 100.

**Comment by BerkieBb** [comment]
You don't have localize the timoutlength from thw config, you can just directly grab the variable from the config

**Comment by IdrisDose** [comment]
> You don't have localize the timoutlength from thw config, you can just directly grab the variable from the config

True, I forgot to remove that, I made a variable initially so I didn't have to F&R each timings. I'll update the PR with just the config option :D

**Pull request merged**
