### PR TITLE
Added support to open the trunk

### PR DESCRIPTION
**Pull request by Terranzin**
User was able to open all doors and hood except trunk.

Added support to open trunk using QB-target

### CODE REVIEW

**Comment by BerkieBb** [comment]
You placed the bones.lua in the wrong folder, it should be in the data folder

**Comment by Terranzin** [comment]
> You placed the bones.lua in the wrong folder, it should be in the data folder

Made a new commit, don´t know why it got placed there to be honest.

**Comment by BerkieBb** [comment]
I'll check it tomorrow if I can

**Comment by BerkieBb** [comment]
Added with better compatibility in V5.1.0, commit in 10 minutes

**Pull request closed without merging**
